### ISSUE TITLE
How much time it takes to train the neural networks? What are machine specs?

### ISSUE THREAD

**Issue by igauravsehrawat** [dwww2012/Accent-Classifier#1]
First thank you for wonderful code and explanation.

**Comment by dwww2012** [comment]
This was trained on GPUs on an AWS EC2 instance--I can't remember the exact specs. It took on the order of tens of minutes to train, as I recall. Not sure how long it would take to train on a normal CPU.

**Comment by igauravsehrawat** [comment]
Thanks for the reply.

Note to others: CPUs are give ups, when dealing with machine learning stuff for real application
